zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")


zn "USER"
do $System.OBJ.LoadDir("/opt/irisbuild/src","ck",,1)

SET tSC = ##class(Ens.Director).StartProduction("DatabaseManager.Production")
WRITE "[ OK ] Start production"

zn "%SYS"
WRITE "[ OK ] Moved to %SYS Namespace"

WRITE "Import Web applications last" 
SET tSC = ##class(Security.Applications).Import("/opt/irisbuild/Application.xml")
write tSC
WRITE "[ OK ] Import Web applications configuration"

halt
