Class DatabaseManager.Messages.SearchDataResponse Extends DatabaseManager.Messages.BasicResponse
{

Property datas As list Of DatabaseManager.Object.Datas;

Storage Default
{
<Data name="SearchDataResponseDefaultData">
<Subscript>"SearchDataResponse"</Subscript>
<Value name="1">
<Value>datas</Value>
</Value>
</Data>
<DefaultData>SearchDataResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
